### ISSUE TITLE
setup.py shows MIT license even if other license is selected during creation

### ISSUE THREAD

**Issue by zahash** [cookiejar/cookietemple#521]
I created a simple python CLI template with argparse, pytest, and Affero license. But the 'classifiers' list in setup.py is showing an MIT license.

classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],

license="MIT",

**Comment by Zethson** [comment]
Ah yeah. We can fix that.
The issue is that those classifiers are not really standardized. Additionally there's no classifier for every license that cookietemple has available.

I guess we will use if statements to depending on the chosen license add the appropriate classifier here.

Thank you for the report!

**Comment by Imipenem** [comment]
Hey,
we fixed this in #528 and will release the fix soon.
