### ISSUE TITLE
Python-lib support

### ISSUE THREAD

**Issue by nasifimtiazohi** [cookiejar/cookietemple#819]
The current python-cli template doesn't come with `setup.py` file. I was looking for a template similar to https://github.com/audreyfeldroy/cookiecutter-pypackage

**Comment by Zethson** [comment]
Hi,

That's because we strongly prefer Poetry over setuptools for packaging. We will no longer have a setup.py based template anymore.
However, we had one earlier you can technically still use it if you install cookietemple 1.2.4. Basically any version before 1.3.x. This one still had a setup.py based template which is pretty similar to Audreys template. However, I would like to strongly encourage you to explore Poetry and to use the most recent template. It has many many improvements.

**Comment by nasifimtiazohi** [comment]
Ok I see. I did not have experience with poetry. Thanks for the response.
